### ISSUE TITLE
Files with just newline separators are not properly converted from Yaml

### ISSUE THREAD

**Issue by isc-tstolker** [lscalese/openapi-common-lib#2]
The issue I raised yesterday on https://openexchange.intersystems.com/package/OpenAPI-Suite turns out to be a matter of properly setting the stream lineTerminator for files on Windows 

I run with docker on windows, which sets the default value for the stream terminator to $CHAR(13,10)
So I had to extend the logic to reset the lineterminator to just $CHAR(10) to make the conversion work.

See https://github.com/lscalese/openapi-common-lib/pull/1 for my fix.

With that, the issue is gone.

**Comment by lscalese** [comment]
Done!
